--
-- Created by MikBac on 21.05.2020
--
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt5180504', 'The Witcher');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0898266', 'The Big Bang Theory');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt6520930', 'Blinded by the Lights');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt2861424', 'Rick and Morty');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt2085059', 'Black Mirror');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt1856010', 'House of Cards');

INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0138704', 'Pi');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0120737', 'The Lord of the Rings: The Fellowship of the Ring');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0167261', 'The Lord of the Rings: The Two Towers');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0167260', 'The Lord of the Rings: The Return of the King');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0363771', 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt2358891', 'The Great Beauty');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt2282829', 'Kac Wawa');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0363029', 'Rick');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0087803', '1984');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt1959409', 'Imaginaerum ');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0126029', 'Shrek');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0298148', 'Shrek 2');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0413267', 'Shrek the Third');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0892791', 'Shrek Forever After');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0111161', 'The Shawshank Redemption');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0068646', 'The Godfather');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0071562', 'The Godfather: Part II');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0468569', 'The Dark Knight');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0050083', '12 Angry Men');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0108052', 'Schindler''s List');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0110912', 'Pulp Fiction');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0060196', 'The Good, the Bad and the Ugly');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0137523', 'Fight Club');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0109830', 'Forrest Gump');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt1375666', 'Inception');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0080684', 'Star Wars: Episode V - The Empire Strikes Back');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0133093', 'The Matrix');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0234215', 'The Matrix Reloaded');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0242653', 'The Matrix Revolutions');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0099685', 'Goodfellas');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0073486', 'One Flew Over the Cuckoo''s Nest');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0114369', 'Se7en');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0102926', 'The Silence of the Lambs');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0038650', 'It''s a Wonderful Life');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt6751668', 'Parasite');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0120689', 'The Green Mile');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0816692', 'Interstellar');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0056058', 'Harakiri');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0110357', 'The Lion King');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt0253474', 'The Pianist');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt9619798', 'The Wrong Missy');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt3152592', 'Scoob!');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt6723592', 'Tenet');
INSERT INTO Movie(pk, id, name) VALUES (default, 'tt7286456', 'Joker');

INSERT INTO Question(pk, description, base_movie_variable, variable_name, start_variable, end_variable, good_value_range) VALUES (default, 'Jak dużo masz wolnego czasu?', 'RUN_TIME','freeTimeBySeasons', 25, 200, 15);
INSERT INTO Question(pk, description, base_movie_variable, variable_name, start_variable, end_variable, good_value_range) VALUES (default, 'Jak bardzo lubisz nowości?', 'RELEASED','newestByRelease', 1990, 2019, 5);
INSERT INTO Question(pk, description, base_movie_variable, variable_name, start_variable, end_variable, good_value_range) VALUES (default, 'Jak bardzo lubisz robić sobie długie przerwy w nauce?', 'TOTAL_SEASONS','lengthByRunTime', 1, 6, 1);
INSERT INTO Question(pk, description, base_movie_variable, variable_name, start_variable, end_variable, good_value_range) VALUES (default, 'Jak bardzo lubisz to co jest popularne?', 'IMDB_VOTES','popularByIMDBVotes', 50000, 300000, 25000);
INSERT INTO Question(pk, description, base_movie_variable, variable_name, start_variable, end_variable, good_value_range) VALUES (default, 'Jak bardzo zgadzasz się z ocenami innych ludzi?', 'METASCORE','scoreByMetascore', 0, 100, 7);
INSERT INTO Question(pk, description, base_movie_variable, variable_name, start_variable, end_variable, good_value_range) VALUES (default, 'Jak bardzo lubisz inne języki?', 'QUANTITY_LANGUAGES','languagesByQuantityOfLanguages', 1, 4, 1);
INSERT INTO Question(pk, description, base_movie_variable, variable_name, start_variable, end_variable, good_value_range) VALUES (default, 'Jak bardzo lubisz globalizację?', 'QUANTITY_COUNTRIES','globalizationByQuantityOfCountries', 1, 4, 1);
